// soundloader.js — shared buffer-loading UI + helpers for every node that plays an
// AudioBuffer (sndfile~ and the granular family). Keeps one file-picker / bundled-sound
// dropdown / drag-and-drop implementation instead of duplicating it per node.
//
// Contract with the node's runtime (returned by create): setBuffer(toneBuf), play(),
// stopPlay(). The decoded audio is stored on node._audio (never serialized); patches
// persist only params.filename and params.src (a path under sounds/).
const T = () => window.Tone;

// sample sounds shipped in sounds/ (generated by sounds/make_sounds.py). Each entry is a
// "<group>/<file>" path; the sub-directory name becomes the dropdown's optgroup label.
export const BUNDLED = [
  'tonal/bell.wav', 'tonal/pluck.wav', 'tonal/drone.wav',
  'vocal/voice-ah.wav',
  'texture/noise-sweep.wav', 'texture/glass-hits.wav',
];
export const baseName = (p) => String(p).split('/').pop();
const groupOf = (p) => (String(p).includes('/') ? String(p).split('/')[0] : ''); // sub-dir = group
const fullSrc = (p) => `sounds/${p}`;
const BUNDLED_SRCS = BUNDLED.map(fullSrc);

// small node-body button that doesn't start a node drag when clicked
export function miniBtn(label) {
  const b = document.createElement('button');
  b.type = 'button';
  b.className = 'mini-btn';
  b.textContent = label;
  b.addEventListener('mousedown', (e) => e.stopPropagation());
  return b;
}

// render() body: filename, bundled-sound dropdown, file/play/stop buttons, drag-and-drop.
// Reusable across any buffer-source node type.
export function soundLoaderRender({ node, body, view, editor }) {
  const rt = () => editor.engine.runtimes.get(node.id);

  const name = document.createElement('div');
  name.className = 'snd-name';
  name.textContent = node.params.filename || (node.params.src ? baseName(node.params.src) : '(no file)');

  const sel = document.createElement('select');
  sel.className = 'snd-select';
  const ph = new Option('▾ bundled sound', '');
  ph.disabled = true; ph.selected = true;
  sel.add(ph);
  // group options into <optgroup>s by sub-directory name
  const groups = new Map();
  BUNDLED.forEach((f) => { const g = groupOf(f) || 'sounds'; (groups.get(g) || groups.set(g, []).get(g)).push(f); });
  for (const [label, files] of groups) {
    const og = document.createElement('optgroup');
    og.label = label;
    files.forEach((f) => og.appendChild(new Option(baseName(f), fullSrc(f))));
    sel.add(og);
  }
  if (node.params.src && BUNDLED_SRCS.includes(node.params.src)) sel.value = node.params.src;
  sel.addEventListener('mousedown', (e) => e.stopPropagation());

  const row = document.createElement('div');
  row.className = 'snd-btns';
  const loadBtn = miniBtn('⇱ file');
  const playBtn = miniBtn('▶');
  const stopBtn = miniBtn('■');
  row.append(loadBtn, playBtn, stopBtn);

  const fileInput = document.createElement('input');
  fileInput.type = 'file';
  fileInput.accept = 'audio/*';
  fileInput.hidden = true;

  // load audio from a URL (bundled sound or object URL from a picked file)
  const loadUrl = async (url, display, revoke = false) => {
    name.textContent = 'decoding…';
    try {
      const buf = new (T().ToneAudioBuffer)();
      await buf.load(url);
      if (revoke) URL.revokeObjectURL(url);
      node._audio = { name: display, buffer: buf };
      editor.onParamChange(node.id, 'filename', display);
      editor.onParamChange(node.id, 'src', revoke ? '' : url); // user files aren't re-loadable by path
      name.textContent = display;
      rt()?.setBuffer?.(buf); // hand the buffer to the live runtime if audio is running
    } catch (e) {
      name.textContent = 'load failed';
      console.error(`[${node.type}] load failed`, url, e);
    }
  };

  loadBtn.addEventListener('click', () => fileInput.click());
  fileInput.addEventListener('change', (e) => {
    const f = e.target.files[0];
    if (f) loadUrl(URL.createObjectURL(f), f.name, true);
    e.target.value = '';
  });
  sel.addEventListener('change', () => { if (sel.value) loadUrl(sel.value, baseName(sel.value)); });
  playBtn.addEventListener('click', () => rt()?.play?.());
  stopBtn.addEventListener('click', () => rt()?.stopPlay?.());
  const doLoad = (file) => { if (file) loadUrl(URL.createObjectURL(file), file.name, true); };

  view.el.addEventListener('dragover', (e) => { e.preventDefault(); view.el.classList.add('dragover'); });
  view.el.addEventListener('dragleave', () => view.el.classList.remove('dragover'));
  view.el.addEventListener('drop', (e) => {
    e.preventDefault();
    view.el.classList.remove('dragover');
    doLoad(e.dataTransfer?.files?.[0]);
  });

  body.append(name, sel, row, fileInput);
}

// create()-side: auto-load a bundled sound referenced by params.src. applyReady(toneBuf)
// receives the decoded buffer (apply it + start playback). No-op if a buffer is already
// present or no src is set.
export async function autoloadSrc(node, applyReady) {
  if (node._audio?.buffer || !node.params.src) return;
  try {
    const buf = new (T().ToneAudioBuffer)();
    await buf.load(node.params.src);
    node._audio = { name: node.params.filename || baseName(node.params.src), buffer: buf };
    applyReady(buf);
  } catch (e) { console.warn(`[${node.type}] autoload failed`, node.params.src, e); }
}
